---
title: "HouseHunters"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(crosstalk)
library(d3scatter)
library(DT)
library(highcharter)
dat <- read.csv("value_house.csv", stringsAsFactors = FALSE)
hunter_dat <- dat %>%
  drop_na(list_price)
```

Map
=======================================================================

Row {data-height=650}
-----------------------------------------------------------------------

### Map of Housing Options
```{r}
getColor <- function(dat) {
  color_vec <- lapply(dat$value_category, function(value_cat) {
    if (value_cat == "high") {
      "blue"
    } else if (value_cat == "med") {
      "green"
    } else {
      "red"
    }
  })
  unlist(color_vec)
}
```

```{r high price, include=FALSE}
# creating high price data, labels, and icons
high_price_dat <- hunter_dat %>%
  filter(price_category == "high")
high_price_labels <- sprintf("<strong>%s</strong><br/>List Price: $%s",
                  high_price_dat$address,
                  scales::comma(high_price_dat$list_price)) %>%
  lapply(htmltools::HTML)
high_price_icons <- awesomeIcons(
  iconColor = 'black',
  markerColor = getColor(high_price_dat)
)
```

```{r med price, include=FALSE}
# creating medium price data, labels, and icons
med_price_dat <- hunter_dat %>%
  filter(price_category == "med")
med_price_labels <- sprintf("<strong>%s</strong><br/>List Price: $%s",
                  med_price_dat$address,
                  scales::comma(med_price_dat$list_price)) %>%
  lapply(htmltools::HTML)
med_price_icons <- awesomeIcons(
  iconColor = 'black',
  markerColor = getColor(med_price_dat)
)
```

```{r low price, include=FALSE}
# creating low price data, labels, and icons
low_price_dat <- hunter_dat %>%
  filter(price_category == "low")
low_price_labels <- sprintf("<strong>%s</strong><br/>List Price: $%s",
                  low_price_dat$address,
                  scales::comma(low_price_dat$list_price)) %>%
  lapply(htmltools::HTML)
low_price_icons <- awesomeIcons(
  iconColor = 'black',
  markerColor = getColor(low_price_dat)
)
```

```{r}
leaflet() %>%
  setView(lng = mean(hunter_dat$longitude),
          lat = mean(hunter_dat$latitude) + 0.075,
          zoom = 10) %>%
  addTiles() %>%
  addAwesomeMarkers(data = high_price_dat,
                    lng = ~longitude,
                    lat = ~latitude,
                    icon = high_price_icons,
                    popup = high_price_labels,
                    group = "High") %>%
  addAwesomeMarkers(data = med_price_dat,
                    lng = ~longitude,
                    lat = ~latitude,
                    icon = med_price_icons,
                    popup = med_price_labels,
                    group = "Medium") %>%
  addAwesomeMarkers(data = low_price_dat,
                    lng = ~longitude,
                    lat = ~latitude,
                    icon = low_price_icons,
                    popup = low_price_labels,
                    group = "Low") %>%
  addLayersControl(
    overlayGroups = c("High", "Medium", "Low"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  htmlwidgets::onRender("
    function() {
            $('.leaflet-control-layers-overlays').prepend('<label style=\"text-align:center\">Price Category</label>');
        }    
  ") %>%
  addLegend(position = "bottomright",
            title = "Value Category",
            colors = c("Blue", "Green", "Red"),
            labels = c("High", "Medium", "Low"))
```

Analysis
=======================================================================

Row {data-height=250}
-----------------------------------------------------------------------

### Data Table

```{r}
hunter_DT <- hunter_dat %>%
  select(address, bed, bathroom, sq_footage, hunter_mins, stewart_mins,
        list_price, price_category, value, value_category) %>%
  mutate(list_price = paste0("$", scales::comma(list_price)),
         hunter_mins = paste0(hunter_mins, " minutes"),
         stewart_mins = paste0(stewart_mins, " minutes"),
         value = round(value, digits = 5)) %>%
  dplyr::rename("Address" = address,
                "List Price" = list_price,
                "Bedrooms" = bed,
                "Bathrooms" = bathroom,
                "Square Footage" = sq_footage,
                "Time to Hunter" = hunter_mins,
                "Time to Stewart" = stewart_mins,
                "List Price" = list_price,
                "Price Category" = price_category,
                "Value Score" = value,
                "Value Category" = value_category)
datatable(hunter_DT,
          height = 600,
          rownames = FALSE)
```

Row {data-height=650 .tabset}
-----------------------------------------------------------------------

### Square Footage vs. Value

```{r, fig.width=30, fig.height=12}
hunter_dat %>%
  mutate(price_category = factor(price_category, levels = c("low", "med", "high"))) %>%
  ggplot(aes(x = sq_footage,
             y = value,
             color = price_category,
             size = 5)) +
  geom_point() +
  theme_bw(base_size = 28) +
  xlab("Square Feet") +
  labs(color = "Price Category") +
  guides(size = FALSE)
```

### Time to Hunter vs. Value

```{r, fig.width=30, fig.height=12}
hunter_dat %>%
  mutate(price_category = factor(price_category, levels = c("low", "med", "high"))) %>%
  ggplot(aes(x = hunter_mins,
             y = value,
             color = price_category,
             size = 5)) +
  geom_point() +
  theme_bw(base_size = 28) +
  xlab("Time to Hunter (minutes)") +
  labs(color = "Price Category") +
  guides(size = FALSE)
```

### Time to Stewart vs. Value

```{r, fig.width=30, fig.height=12}
hunter_dat %>%
  mutate(price_category = factor(price_category, levels = c("low", "med", "high"))) %>%
  ggplot(aes(x = stewart_mins,
             y = value,
             color = price_category,
             size = 5)) +
  geom_point() +
  theme_bw(base_size = 28) +
  xlab("Time to Stewart (minutes)") +
  labs(color = "Price Category") +
  guides(size = FALSE)
```

Row {data-height=650 .tabset}
-----------------------------------------------------------------------

### High Value

```{r}
high_val_dat <- hunter_dat %>%
  filter(value_category == "high")
```

### Medium Value

```{r}
med_val_dat <- hunter_dat %>%
  filter(value_category == "med")
```

### Low Value

```{r}
low_val_dat <- hunter_dat %>%
  filter(value_category == "low")
```

Recommendations
=======================================================================